# Copyright 2021 Cornellius Metto
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  http-output:
    default: ""
    description: Falco alerts will be sent to the HTTP[s] URL defined by this option
    type: string
